{% set name = "napari-file-watcher" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-file-watcher-{{ version }}.tar.gz
  sha256: f3f9322b703d0eef93631f70198f861cb2b279ae59e879abc723d9961963bf37
  patches:
    - qtpy.patch
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - h5py
    - napari
    - ome-zarr
    - python >=3.8
    - qscintilla2
    - qtpy
    - zarr

test:
  imports:
    - napari_file_watcher
    - napari_file_watcher.guitools
    - napari_file_watcher.main_module
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-file-watcher
  summary: A napari plugin for file watching
  license: GPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/kasasxav/napari-file-watcher

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - kasasxav
